name: 'Android setup'
description: 'Setup VM for Android'

runs:
  using: "composite"
  steps:
  - name: Set up JDK
    uses: actions/setup-java@v6
    with:
      distribution: 'temurin'
      java-version: '21'

  - name: Verify gradle scripts are not modified 
    uses: gradle/actions/wrapper-validation@v6

  - name: Setup Android SDK
    uses: android-actions/setup-android@v4 
    
  - name: Setup Gradle and cache dependencies between builds 
    uses: gradle/gradle-build-action@v3